name: estrelladelevantejm
recipe: drupal9
config:
  webroot: web
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  phpmyadmin:
    - phpmyadmin.estrelladelevantejm.lndo.site
